:as-is-paths to skip value conversion for specific properties
tolitius/cprop pull request #40
Opened 2021-05-02 00:33 UTC by codeperfector

2021-05-28 21:29 UTC, tolitius requested changes
thanks for the contribution!
I left a comment to refactor logic into a function

2021-05-28 21:29 UTC, tolitius commented on src/cprop/source.cljc
> +                   [path (->> (assoc opts :as-is? (or (:as-is? opts) (and as-is-paths (as-is-paths path))))
this is repeated 3 times in 3 functions
let's refactor it out into it's own function that takes opts, and path and returns opts

```clojure
(defn with-as-is [{:keys [as-is?
                          as-is-paths] :as opts} path]
  (assoc opts :as-is? (or as-is?
                          (and as-is-paths
                               (as-is-paths path))))
```

then the let block for all the places this is used would look somm like:

```clojure
(let [path (sysprop->path k opts)]
  [path (->> (with-as-is opts path)
             (str->value v))])
```

2021-05-29 20:05 UTC, codeperfector commented
I performed the changes requested. I also added a README section for this feature.

2021-05-30 18:06 UTC, tolitius requested changes
thanks for the changes
I added a few cleanup comments

2021-05-30 18:06 UTC, tolitius commented on README.md
> +(load-config :as-is-paths #{'(:io :http :pool :socket-timeout)})
for sequences, in Clojure, lists "`'()`" are rarely used in APIs, and vectors are preferred
lists are good to you when you actually need a linked list semantics: i.e. parsing code, append, etc.

so the above example would be:

```clojure
(load-config :as-is-paths #{[:io :http :pool :socket-timeout]})
```

also, in order to convey the message of these paths being a set it is good to give a few paths as an example:

```clojure
(load-config :as-is-paths #{[:io :http :pool :socket-timeout]
                            [:datomic :max-conn]
                            [:some :other :path]})
```

2021-05-30 18:06 UTC, tolitius commented on src/cprop/source.cljc
> +                                 (as-is-paths path)))))
format as (two spaces below the form):
```clojure
(defn ^:private with-as-is
  [{:keys [as-is? as-is-paths] :as opts} path]
  (assoc opts :as-is? (or as-is?
                          (and as-is-paths
                               (as-is-paths path)))))
```
so it is consistent with the codebase

2021-05-30 18:06 UTC, tolitius commented on src/cprop/source.cljc
> +                              (str->value v))])))
format:
```clojure
(map (fn [[k v]]
       (let [path (env->path k opts)]
         [path (->> (with-as-is opts path)
                    (str->value v))])))
```

2021-05-30 18:06 UTC, tolitius commented on src/cprop/source.cljc
> +                              (str->value v))])))
format:
```clojure
(map (fn [[k v]]
       (let [path (sysprop->path k opts)]
         [path (->> (with-as-is opts path)
                    (str->value v))])))
```

2021-05-30 18:06 UTC, tolitius commented on src/cprop/source.cljc
> +                                                  v)))])))
format:
```clojure
(map (fn [[k v]]
       (let [prop-path (prop-key->path k opts)]
         [prop-path (->> (with-as-is opts prop-path)
                         (str->value (if-not (false? parse-seqs?) ;; could be nil, which is true in this case
                                       (prop-seq v)
                                       v)))])))
```

2021-05-30 18:06 UTC, tolitius commented on test/cprop/test/core.cljc
> +        props-as-is-path  (from-system-props {:as-is-paths #{'(:io :http :pool :socket-timeout)}})
do add cases with a few paths to make sure it works with sets of paths
also `'()` to `[]` for paths

2021-06-05 00:22 UTC, codeperfector commented
@tolitius Thank you. I made the changes you requested.

2021-06-07 22:42 UTC, tolitius commented
@codeperfector 
thanks, looks great!

2021-06-07 22:42 UTC, merged